JEDEC(0, 0x01, "AMD")
JEDEC(0, 0x02, "AMI")
JEDEC(0, 0x83, "Fairchild")
JEDEC(0, 0x04, "Fujitsu")
JEDEC(0, 0x85, "GTE")
JEDEC(0, 0x86, "Harris")
JEDEC(0, 0x07, "Hitachi")
JEDEC(0, 0x08, "Inmos")
JEDEC(0, 0x89, "Intel")
JEDEC(0, 0x8A, "I.T.T.")
JEDEC(0, 0x0B, "Intersil")
JEDEC(0, 0x8C, "Monolithic Memories")
JEDEC(0, 0x0D, "Mostek")
JEDEC(0, 0x0E, "Freescale (Motorola)")
JEDEC(0, 0x8F, "National")
JEDEC(0, 0x10, "NEC")
JEDEC(0, 0x91, "RCA")
JEDEC(0, 0x92, "Raytheon")
JEDEC(0, 0x13, "Conexant (Rockwell)")
JEDEC(0, 0x94, "Seeq")
JEDEC(0, 0x15, "NXP (Philips)")
JEDEC(0, 0x16, "Synertek")
JEDEC(0, 0x97, "Texas Instruments")
JEDEC(0, 0x98, "Toshiba")
JEDEC(0, 0x19, "Xicor")
JEDEC(0, 0x1A, "Zilog")
JEDEC(0, 0x9B, "Eurotechnique")
JEDEC(0, 0x1C, "Mitsubishi")
JEDEC(0, 0x9D, "Lucent (AT&T)")
JEDEC(0, 0x9E, "Exel")
JEDEC(0, 0x1F, "Atmel")
JEDEC(0, 0x20, "STMicroelectronics")
JEDEC(0, 0xA1, "Lattice Semi.")
JEDEC(0, 0xA2, "NCR")
JEDEC(0, 0x23, "Wafer Scale Integration")
JEDEC(0, 0xA4, "IBM")
JEDEC(0, 0x25, "Tristar")
JEDEC(0, 0x26, "Visic")
JEDEC(0, 0xA7, "Intl. CMOS Technology")
JEDEC(0, 0xA8, "SSSI")
JEDEC(0, 0x29, "MicrochipTechnology")
JEDEC(0, 0x2A, "Ricoh Ltd.")
JEDEC(0, 0xAB, "VLSI")
JEDEC(0, 0x2C, "Micron Technology")
JEDEC(0, 0xAD, "SK Hynix")
JEDEC(0, 0xAE, "OKI Semiconductor")
JEDEC(0, 0x2F, "ACTEL")
JEDEC(0, 0xB0, "Sharp")
JEDEC(0, 0x31, "Catalyst")
JEDEC(0, 0x32, "Panasonic")
JEDEC(0, 0xB3, "IDT")
JEDEC(0, 0x34, "Cypress")
JEDEC(0, 0xB5, "DEC")
JEDEC(0, 0xB6, "LSI Logic")
JEDEC(0, 0x37, "Zarlink (Plessey)")
JEDEC(0, 0x38, "UTMC")
JEDEC(0, 0xB9, "Thinking Machine")
JEDEC(0, 0xBA, "Thomson CSF")
JEDEC(0, 0x3B, "Integrated CMOS (Vertex)")
JEDEC(0, 0xBC, "Honeywell")
JEDEC(0, 0x3D, "Tektronix")
JEDEC(0, 0x3E, "Oracle Corporation")
JEDEC(0, 0xBF, "Silicon Storage Technology")
JEDEC(0, 0x40, "ProMos/Mosel Vitelic")
JEDEC(0, 0xC1, "Infineon (Siemens)")
JEDEC(0, 0xC2, "Macronix")
JEDEC(0, 0x43, "Xerox")
JEDEC(0, 0xC4, "Plus Logic")
JEDEC(0, 0x45, "SanDisk Corporation")
JEDEC(0, 0x46, "Elan Circuit Tech.")
JEDEC(0, 0xC7, "European Silicon Str.")
JEDEC(0, 0xC8, "Apple Computer")
JEDEC(0, 0x49, "Xilinx")
JEDEC(0, 0x4A, "Compaq")
JEDEC(0, 0xCB, "Protocol Engines")
JEDEC(0, 0x4C, "SCI")
JEDEC(0, 0xCD, "Seiko Instruments")
JEDEC(0, 0xCE, "Samsung")
JEDEC(0, 0x4F, "I3 Design System")
JEDEC(0, 0xD0, "Klic")
JEDEC(0, 0x51, "Crosspoint Solutions")
JEDEC(0, 0x52, "Alliance Semiconductor")
JEDEC(0, 0xD3, "Tandem")
JEDEC(0, 0x54, "Hewlett-Packard")
JEDEC(0, 0xD5, "Integrated Silicon Solutions")
JEDEC(0, 0xD6, "Brooktree")
JEDEC(0, 0x57, "New Media")
JEDEC(0, 0x58, "MHS Electronic")
JEDEC(0, 0xD9, "Performance Semi.")
JEDEC(0, 0xDA, "Winbond Electronic")
JEDEC(0, 0x5B, "Kawasaki Steel")
JEDEC(0, 0xDC, "Bright Micro")
JEDEC(0, 0x5D, "TECMAR")
JEDEC(0, 0x5E, "Exar")
JEDEC(0, 0xDF, "PCMCIA")
JEDEC(0, 0xE0, "LG Semi (Goldstar)")
JEDEC(0, 0x61, "Northern Telecom")
JEDEC(0, 0x62, "Sanyo")
JEDEC(0, 0xE3, "Array Microsystems")
JEDEC(0, 0x64, "Crystal Semiconductor")
JEDEC(0, 0xE5, "Analog Devices")
JEDEC(0, 0xE6, "PMC-Sierra")
JEDEC(0, 0x67, "Asparix")
JEDEC(0, 0x68, "Convex Computer")
JEDEC(0, 0xE9, "Quality Semiconductor")
JEDEC(0, 0xEA, "Nimbus Technology")
JEDEC(0, 0x6B, "Transwitch")
JEDEC(0, 0xEC, "Micronas (ITT Intermetall)")
JEDEC(0, 0x6D, "Cannon")
JEDEC(0, 0x6E, "Altera")
JEDEC(0, 0xEF, "NEXCOM")
JEDEC(0, 0x70, "Qualcomm")
JEDEC(0, 0xF1, "Sony")
JEDEC(0, 0xF2, "Cray Research")
JEDEC(0, 0x73, "AMS(Austria Micro)")
JEDEC(0, 0xF4, "Vitesse")
JEDEC(0, 0x75, "Aster Electronics")
JEDEC(0, 0x76, "Bay Networks (Synoptic)")
JEDEC(0, 0xF7, "Zentrum/ZMD")
JEDEC(0, 0xF8, "TRW")
JEDEC(0, 0x79, "Thesys")
JEDEC(0, 0x7A, "Solbourne Computer")
JEDEC(0, 0xFB, "Allied-Signal")
JEDEC(0, 0x7C, "Dialog Semiconductor")
JEDEC(0, 0xFD, "Media Vision")
JEDEC(0, 0xFE, "Numonyx Corporation")

JEDEC(1, 0x01, "Cirrus Logic")
JEDEC(1, 0x02, "National Instruments")
JEDEC(1, 0x83, "ILC Data Device")
JEDEC(1, 0x04, "Alcatel Mietec")
JEDEC(1, 0x85, "Micro Linear")
JEDEC(1, 0x86, "Univ. of NC")
JEDEC(1, 0x07, "JTAG Technologies")
JEDEC(1, 0x08, "BAE Systems (Loral)")
JEDEC(1, 0x89, "Nchip")
JEDEC(1, 0x8A, "Galileo Tech")
JEDEC(1, 0x0B, "Bestlink Systems")
JEDEC(1, 0x8C, "Graychip")
JEDEC(1, 0x0D, "GENNUM")
JEDEC(1, 0x0E, "VideoLogic")
JEDEC(1, 0x8F, "Robert Bosch")
JEDEC(1, 0x10, "Chip Express")
JEDEC(1, 0x91, "DATARAM")
JEDEC(1, 0x92, "United Microelectronics Corp.")
JEDEC(1, 0x13, "TCSI")
JEDEC(1, 0x94, "Smart Modular")
JEDEC(1, 0x15, "Hughes Aircraft")
JEDEC(1, 0x16, "Lanstar Semiconductor")
JEDEC(1, 0x97, "Qlogic")
JEDEC(1, 0x98, "Kingston")
JEDEC(1, 0x19, "Music Semi")
JEDEC(1, 0x1A, "Ericsson Components")
JEDEC(1, 0x9B, "SpaSE")
JEDEC(1, 0x1C, "Eon Silicon Devices")
JEDEC(1, 0x9D, "Integrated Silicon Solution (ISSI)")
JEDEC(1, 0x9E, "DoD")
JEDEC(1, 0x1F, "Integ. Memories Tech.")
JEDEC(1, 0x20, "Corollary Inc.")
JEDEC(1, 0xA1, "Dallas Semiconductor")
JEDEC(1, 0xA2, "Omnivision")
JEDEC(1, 0x23, "EIV(Switzerland)")
JEDEC(1, 0xA4, "Novatel Wireless")
JEDEC(1, 0x25, "Zarlink (Mitel)")
JEDEC(1, 0x26, "Clearpoint")
JEDEC(1, 0xA7, "Cabletron")
JEDEC(1, 0xA8, "STEC (Silicon Tech)")
JEDEC(1, 0x29, "Vanguard")
JEDEC(1, 0x2A, "Hagiwara Sys-Com")
JEDEC(1, 0xAB, "Vantis")
JEDEC(1, 0x2C, "Celestica")
JEDEC(1, 0xAD, "Century")
JEDEC(1, 0xAE, "Hal Computers")
JEDEC(1, 0x2F, "Rohm Company Ltd.")
JEDEC(1, 0xB0, "Juniper Networks")
JEDEC(1, 0x31, "Libit Signal Processing")
JEDEC(1, 0x32, "Mushkin Enhanced Memory")
JEDEC(1, 0xB3, "Tundra Semiconductor")
JEDEC(1, 0x34, "Adaptec Inc.")
JEDEC(1, 0xB5, "LightSpeed Semi.")
JEDEC(1, 0xB6, "ZSP Corp.")
JEDEC(1, 0x37, "AMIC Technology")
JEDEC(1, 0x38, "Adobe Systems")
JEDEC(1, 0xB9, "Dynachip")
JEDEC(1, 0xBA, "PNY Technologies, Inc.")
JEDEC(1, 0x3B, "Newport Digital")
JEDEC(1, 0xBC, "MMC Networks")
JEDEC(1, 0x3D, "T Square")
JEDEC(1, 0x3E, "Seiko Epson")
JEDEC(1, 0xBF, "Broadcom")
JEDEC(1, 0x40, "Viking Components")
JEDEC(1, 0xC1, "V3 Semiconductor")
JEDEC(1, 0xC2, "Flextronics (Orbit Semiconductor)")
JEDEC(1, 0x43, "Suwa Electronics")
JEDEC(1, 0xC4, "Transmeta")
JEDEC(1, 0x45, "Micron CMS")
JEDEC(1, 0x46, "American Computer & Digital Components Inc.")
JEDEC(1, 0x00, "Enhance 3000 Inc.")
JEDEC(1, 0xC8, "Tower Semiconductor")
JEDEC(1, 0x49, "CPU Design")
JEDEC(1, 0x4A, "Price Point")
JEDEC(1, 0xCB, "Maxim Integrated Product")
JEDEC(1, 0x4C, "Tellabs")
JEDEC(1, 0xCD, "Centaur Technology")
JEDEC(1, 0xCE, "Unigen Corporation")
JEDEC(1, 0x4F, "Transcend Information")
JEDEC(1, 0xD0, "Memory Card Technology")
JEDEC(1, 0x51, "CKD Corporation Ltd.")
JEDEC(1, 0x52, "Capital Instruments, Inc.")
JEDEC(1, 0xD3, "Aica Kogyo, Ltd.")
JEDEC(1, 0x54, "Linvex Technology")
JEDEC(1, 0xD5, "MSC Vertriebs GmbH")
JEDEC(1, 0xD6, "AKM Company, Ltd.")
JEDEC(1, 0x57, "Dynamem, Inc.")
JEDEC(1, 0x58, "NERA ASA")
JEDEC(1, 0xD9, "GSI Technology")
JEDEC(1, 0xDA, "Dane-Elec (C Memory)")
JEDEC(1, 0x5B, "Acorn Computers")
JEDEC(1, 0xDC, "Lara Technology")
JEDEC(1, 0x5D, "Oak Technology, Inc.")
JEDEC(1, 0x5E, "Itec Memory")
JEDEC(1, 0xDF, "Tanisys Technology")
JEDEC(1, 0xE0, "Truevision")
JEDEC(1, 0x61, "Wintec Industries")
JEDEC(1, 0x62, "Super PC Memory")
JEDEC(1, 0xE3, "MGV Memory")
JEDEC(1, 0x64, "Galvantech")
JEDEC(1, 0xE5, "Gadzoox Networks")
JEDEC(1, 0xE6, "Multi Dimensional Cons.")
JEDEC(1, 0x67, "GateField")
JEDEC(1, 0x68, "Integrated Memory System")
JEDEC(1, 0xE9, "Triscend")
JEDEC(1, 0xEA, "XaQti")
JEDEC(1, 0x6B, "Goldenram")
JEDEC(1, 0xEC, "Clear Logic")
JEDEC(1, 0x6D, "Cimaron Communications")
JEDEC(1, 0x6E, "Nippon Steel Semi. Corp.")
JEDEC(1, 0xEF, "Advantage Memory")
JEDEC(1, 0x70, "AMCC")
JEDEC(1, 0xF1, "LeCroy")
JEDEC(1, 0xF2, "Yamaha Corporation")
JEDEC(1, 0x73, "Digital Microwave")
JEDEC(1, 0xF4, "NetLogic Microsystems")
JEDEC(1, 0x75, "MIMOS Semiconductor")
JEDEC(1, 0x76, "Advanced Fibre")
JEDEC(1, 0xF7, "BF Goodrich Data.")
JEDEC(1, 0xF8, "Epigram")
JEDEC(1, 0x79, "Acbel Polytech Inc.")
JEDEC(1, 0x7A, "Apacer Technology")
JEDEC(1, 0xFB, "Admor Memory")
JEDEC(1, 0x7C, "FOXCONN")
JEDEC(1, 0xFD, "Quadratics Superconductor")
JEDEC(1, 0xFE, "COM")

JEDEC(2, 0x01, "Camintonn Corporation")
JEDEC(2, 0x02, "ISOA Incorporated")
JEDEC(2, 0x83, "Agate Semiconductor")
JEDEC(2, 0x04, "ADMtek Incorporated")
JEDEC(2, 0x85, "HYPERTEC")
JEDEC(2, 0x86, "Adhoc Technologies")
JEDEC(2, 0x07, "MOSAID Technologies")
JEDEC(2, 0x08, "Ardent Technologies")
JEDEC(2, 0x89, "Switchcore")
JEDEC(2, 0x8A, "Cisco Systems, Inc.")
JEDEC(2, 0x0B, "Allayer Technologies")
JEDEC(2, 0x8C, "WorkX AG (Wichman)")
JEDEC(2, 0x0D, "Oasis Semiconductor")
JEDEC(2, 0x0E, "Novanet Semiconductor")
JEDEC(2, 0x8F, "E-M Solutions")
JEDEC(2, 0x10, "Power General")
JEDEC(2, 0x91, "Advanced Hardware Arch.")
JEDEC(2, 0x92, "Inova Semiconductors GmbH")
JEDEC(2, 0x13, "Telocity")
JEDEC(2, 0x94, "Delkin Devices")
JEDEC(2, 0x15, "Symagery Microsystems")
JEDEC(2, 0x16, "C-Port Corporation")
JEDEC(2, 0x97, "SiberCore Technologies")
JEDEC(2, 0x98, "Southland Microsystems")
JEDEC(2, 0x19, "Malleable Technologies")
JEDEC(2, 0x1A, "Kendin Communications")
JEDEC(2, 0x9B, "Great Technology Microcomputer")
JEDEC(2, 0x1C, "Sanmina Corporation")
JEDEC(2, 0x9D, "HADCO Corporation")
JEDEC(2, 0x9E, "Corsair")
JEDEC(2, 0x1F, "Actrans System Inc.")
JEDEC(2, 0x20, "ALPHA Technologies")
JEDEC(2, 0xA1, "Silicon Laboratories, Inc. (Cygnal)")
JEDEC(2, 0xA2, "Artesyn Technologies")
JEDEC(2, 0x23, "Align Manufacturing")
JEDEC(2, 0xA4, "Peregrine Semiconductor")
JEDEC(2, 0x25, "Chameleon Systems")
JEDEC(2, 0x26, "Aplus Flash Technology")
JEDEC(2, 0xA7, "MIPS Technologies")
JEDEC(2, 0xA8, "Chrysalis ITS")
JEDEC(2, 0x29, "ADTEC Corporation")
JEDEC(2, 0x2A, "Kentron Technologies")
JEDEC(2, 0xAB, "Win Technologies")
JEDEC(2, 0x2C, "Tezzaron Semiconductor")
JEDEC(2, 0xAD, "Extreme Packet Devices")
JEDEC(2, 0xAE, "RF Micro Devices")
JEDEC(2, 0x2F, "Siemens AG")
JEDEC(2, 0xB0, "Sarnoff Corporation")
JEDEC(2, 0x31, "Itautec SA")
JEDEC(2, 0x32, "Radiata Inc.")
JEDEC(2, 0xB3, "Benchmark Elect. (AVEX)")
JEDEC(2, 0x34, "Legend")
JEDEC(2, 0xB5, "SpecTek Incorporated")
JEDEC(2, 0xB6, "Hi/fn")
JEDEC(2, 0x37, "Enikia Incorporated")
JEDEC(2, 0x38, "SwitchOn Networks")
JEDEC(2, 0xB9, "AANetcom Incorporated")
JEDEC(2, 0xBA, "Micro Memory Bank")
JEDEC(2, 0x3B, "ESS Technology")
JEDEC(2, 0xBC, "Virata Corporation")
JEDEC(2, 0x3D, "Excess Bandwidth")
JEDEC(2, 0x3E, "West Bay Semiconductor")
JEDEC(2, 0xBF, "DSP Group")
JEDEC(2, 0x40, "Newport Communications")
JEDEC(2, 0xC1, "Chip2Chip Incorporated")
JEDEC(2, 0xC2, "Phobos Corporation")
JEDEC(2, 0x43, "Intellitech Corporation")
JEDEC(2, 0xC4, "Nordic VLSI ASA")
JEDEC(2, 0x45, "Ishoni Networks")
JEDEC(2, 0x46, "Silicon Spice")
JEDEC(2, 0xC7, "Alchemy Semiconductor")
JEDEC(2, 0xC8, "Agilent Technologies")
JEDEC(2, 0x49, "Centillium Communications")
JEDEC(2, 0x4A, "W.L. Gore")
JEDEC(2, 0xCB, "HanBit Electronics")
JEDEC(2, 0x4C, "GlobeSpan")
JEDEC(2, 0x14, "Element 14")
JEDEC(2, 0xCE, "Pycon")
JEDEC(2, 0x4F, "Saifun Semiconductors")
JEDEC(2, 0xD0, "Sibyte, Incorporated")
JEDEC(2, 0x51, "MetaLink Technologies")
JEDEC(2, 0x52, "Feiya Technology")
JEDEC(2, 0xD3, "I & C Technology")
JEDEC(2, 0x54, "Shikatronics")
JEDEC(2, 0xD5, "Elektrobit")
JEDEC(2, 0xD6, "Megic")
JEDEC(2, 0x57, "Com-Tier")
JEDEC(2, 0x58, "Malaysia Micro Solutions")
JEDEC(2, 0xD9, "Hyperchip")
JEDEC(2, 0xDA, "Gemstone Communications")
JEDEC(2, 0x5B, "Anadigm (Anadyne)")
JEDEC(2, 0xDC, "ParData")
JEDEC(2, 0x5D, "Mellanox Technologies")
JEDEC(2, 0x5E, "Tenx Technologies")
JEDEC(2, 0xDF, "Helix AG")
JEDEC(2, 0xE0, "Domosys")
JEDEC(2, 0x61, "Skyup Technology")
JEDEC(2, 0x62, "HiNT Corporation")
JEDEC(2, 0xE3, "Chiaro")
JEDEC(2, 0x64, "MDT Technologies GmbH")
JEDEC(2, 0xE5, "Exbit Technology A/S")
JEDEC(2, 0xE6, "Integrated Technology Express")
JEDEC(2, 0x67, "AVED Memory")
JEDEC(2, 0x68, "Legerity")
JEDEC(2, 0xE9, "Jasmine Networks")
JEDEC(2, 0xEA, "Caspian Networks")
JEDEC(2, 0x6B, "nCUBE")
JEDEC(2, 0xEC, "Silicon Access Networks")
JEDEC(2, 0x6D, "FDK Corporation")
JEDEC(2, 0x6E, "High Bandwidth Access")
JEDEC(2, 0xEF, "MultiLink Technology")
JEDEC(2, 0x70, "BRECIS")
JEDEC(2, 0xF1, "World Wide Packets")
JEDEC(2, 0xF2, "APW")
JEDEC(2, 0x73, "Chicory Systems")
JEDEC(2, 0xF4, "Xstream Logic")
JEDEC(2, 0x75, "Fast-Chip")
JEDEC(2, 0x76, "Zucotto Wireless")
JEDEC(2, 0xF7, "Realchip")
JEDEC(2, 0xF8, "Galaxy Power")
JEDEC(2, 0x79, "eSilicon")
JEDEC(2, 0x7A, "Morphics Technology")
JEDEC(2, 0xFB, "Accelerant Networks")
JEDEC(2, 0x7C, "Silicon Wave")
JEDEC(2, 0xFD, "SandCraft")
JEDEC(2, 0xFE, "Elpida")

JEDEC(3, 0x01, "Solectron")
JEDEC(3, 0x02, "Optosys Technologies")
JEDEC(3, 0x83, "Buffalo (Formerly Melco)")
JEDEC(3, 0x04, "TriMedia Technologies")
JEDEC(3, 0x85, "Cyan Technologies")
JEDEC(3, 0x86, "Global Locate")
JEDEC(3, 0x07, "Optillion")
JEDEC(3, 0x08, "Terago Communications")
JEDEC(3, 0x89, "Ikanos Communications")
JEDEC(3, 0x8A, "Princeton Technology")
JEDEC(3, 0x0B, "Nanya Technology")
JEDEC(3, 0x8C, "Elite Flash Storage")
JEDEC(3, 0x0D, "Mysticom")
JEDEC(3, 0x0E, "LightSand Communications")
JEDEC(3, 0x8F, "ATI Technologies")
JEDEC(3, 0x10, "Agere Systems")
JEDEC(3, 0x91, "NeoMagic")
JEDEC(3, 0x92, "AuroraNetics")
JEDEC(3, 0x13, "Golden Empire")
JEDEC(3, 0x94, "Mushkin")
JEDEC(3, 0x15, "Tioga Technologies")
JEDEC(3, 0x16, "Netlist")
JEDEC(3, 0x97, "TeraLogic")
JEDEC(3, 0x98, "Cicada Semiconductor")
JEDEC(3, 0x19, "Centon Electronics")
JEDEC(3, 0x1A, "Tyco Electronics")
JEDEC(3, 0x9B, "Magis Works")
JEDEC(3, 0x1C, "Zettacom")
JEDEC(3, 0x9D, "Cogency Semiconductor")
JEDEC(3, 0x9E, "Chipcon AS")
JEDEC(3, 0x1F, "Aspex Technology")
JEDEC(3, 0x20, "F5 Networks")
JEDEC(3, 0xA1, "Programmable Silicon Solutions")
JEDEC(3, 0xA2, "ChipWrights")
JEDEC(3, 0x23, "Acorn Networks")
JEDEC(3, 0xA4, "Quicklogic")
JEDEC(3, 0x25, "Kingmax Semiconductor")
JEDEC(3, 0x26, "BOPS")
JEDEC(3, 0xA7, "Flasys")
JEDEC(3, 0xA8, "BitBlitz Communications")
JEDEC(3, 0x29, "eMemory Technology")
JEDEC(3, 0x2A, "Procket Networks")
JEDEC(3, 0xAB, "Purple Ray")
JEDEC(3, 0x2C, "Trebia Networks")
JEDEC(3, 0xAD, "Delta Electronics")
JEDEC(3, 0xAE, "Onex Communications")
JEDEC(3, 0x2F, "Ample Communications")
JEDEC(3, 0xB0, "Memory Experts Intl")
JEDEC(3, 0x31, "Astute Networks")
JEDEC(3, 0x32, "Azanda Network Devices")
JEDEC(3, 0xB3, "Dibcom")
JEDEC(3, 0x34, "Tekmos")
JEDEC(3, 0xB5, "API NetWorks")
JEDEC(3, 0xB6, "Bay Microsystems")
JEDEC(3, 0x37, "Firecron Ltd")
JEDEC(3, 0x38, "Resonext Communications")
JEDEC(3, 0xB9, "Tachys Technologies")
JEDEC(3, 0xBA, "Equator Technology")
JEDEC(3, 0x3B, "Concept Computer")
JEDEC(3, 0xBC, "SILCOM")
JEDEC(3, 0x3D, "Dlabs")
JEDEC(3, 0x3E, "c’t Magazine")
JEDEC(3, 0xBF, "Sanera Systems")
JEDEC(3, 0x40, "Silicon Packets")
JEDEC(3, 0xC1, "Viasystems Group")
JEDEC(3, 0xC2, "Simtek")
JEDEC(3, 0x43, "Semicon Devices Singapore")
JEDEC(3, 0xC4, "Satron Handelsges")
JEDEC(3, 0x45, "Improv Systems")
JEDEC(3, 0x46, "INDUSYS GmbH")
JEDEC(3, 0xC7, "Corrent")
JEDEC(3, 0xC8, "Infrant Technologies")
JEDEC(3, 0x49, "Ritek Corp")
JEDEC(3, 0x4A, "empowerTel Networks")
JEDEC(3, 0xCB, "Hypertec")
JEDEC(3, 0x4C, "Cavium Networks")
JEDEC(3, 0xCD, "PLX Technology")
JEDEC(3, 0xCE, "Massana Design")
JEDEC(3, 0x4F, "Intrinsity")
JEDEC(3, 0xD0, "Valence Semiconductor")
JEDEC(3, 0x51, "Terawave Communications")
JEDEC(3, 0x52, "IceFyre Semiconductor")
JEDEC(3, 0xD3, "Primarion")
JEDEC(3, 0x54, "Picochip Designs Ltd")
JEDEC(3, 0xD5, "Silverback Systems")
JEDEC(3, 0xD6, "Jade Star Technologies")
JEDEC(3, 0x57, "Pijnenburg Securealink")
JEDEC(3, 0x58, "takeMS - Ultron AG")
JEDEC(3, 0xD9, "Cambridge Silicon Radio")
JEDEC(3, 0xDA, "Swissbit")
JEDEC(3, 0x5B, "Nazomi Communications")
JEDEC(3, 0xDC, "eWave System")
JEDEC(3, 0x5D, "Rockwell Collins")
JEDEC(3, 0x5E, "Picocel Co. Ltd. (Paion)")
JEDEC(3, 0xDF, "Alphamosaic Ltd")
JEDEC(3, 0xE0, "Sandburst")
JEDEC(3, 0x61, "SiCon Video")
JEDEC(3, 0x62, "NanoAmp Solutions")
JEDEC(3, 0xE3, "Ericsson Technology")
JEDEC(3, 0x64, "PrairieComm")
JEDEC(3, 0xE5, "Mitac International")
JEDEC(3, 0xE6, "Layer N Networks")
JEDEC(3, 0x67, "MtekVision (Atsana)")
JEDEC(3, 0x68, "Allegro Networks")
JEDEC(3, 0xE9, "Marvell Semiconductors")
JEDEC(3, 0xEA, "Netergy Microelectronic")
JEDEC(3, 0x6B, "NVIDIA")
JEDEC(3, 0xEC, "Internet Machines")
JEDEC(3, 0x6D, "Memorysolution GmbH")
JEDEC(3, 0x6E, "Litchfield Communication")
JEDEC(3, 0xEF, "Accton Technology")
JEDEC(3, 0x70, "Teradiant Networks")
JEDEC(3, 0xF1, "Scaleo Chip")
JEDEC(3, 0xF2, "Cortina Systems")
JEDEC(3, 0x73, "RAM Components")
JEDEC(3, 0xF4, "Raqia Networks")
JEDEC(3, 0x75, "ClearSpeed")
JEDEC(3, 0x76, "Matsushita Battery")
JEDEC(3, 0xF7, "Xelerated")
JEDEC(3, 0xF8, "SimpleTech")
JEDEC(3, 0x79, "Utron Technology")
JEDEC(3, 0x7A, "Astec International")
JEDEC(3, 0xFB, "AVM gmbH")
JEDEC(3, 0x7C, "Redux Communications")
JEDEC(3, 0xFD, "Dot Hill Systems")
JEDEC(3, 0xFE, "TeraChip")

JEDEC(4, 0x01, "T-RAM Incorporated")
JEDEC(4, 0x02, "Innovics Wireless")
JEDEC(4, 0x83, "Teknovus")
JEDEC(4, 0x04, "KeyEye Communications")
JEDEC(4, 0x85, "Runcom Technologies")
JEDEC(4, 0x86, "RedSwitch")
JEDEC(4, 0x07, "Dotcast")
JEDEC(4, 0x08, "Silicon Mountain Memory")
JEDEC(4, 0x89, "Signia Technologies")
JEDEC(4, 0x8A, "Pixim")
JEDEC(4, 0x0B, "Galazar Networks")
JEDEC(4, 0x8C, "White Electronic Designs")
JEDEC(4, 0x0D, "Patriot Scientific")
JEDEC(4, 0x0E, "Neoaxiom Corporation")
JEDEC(4, 0x8F, "Y Power Technology")
JEDEC(4, 0x10, "Scaleo Chip")
JEDEC(4, 0x91, "Potentia Power Systems")
JEDEC(4, 0x92, "C-guys Incorporated")
JEDEC(4, 0x13, "Digital Communications Technology Incorporated")
JEDEC(4, 0x94, "Silicon-Based Technology")
JEDEC(4, 0x15, "Fulcrum Microsystems")
JEDEC(4, 0x16, "Positivo Informatica Ltd")
JEDEC(4, 0x97, "XIOtech Corporation")
JEDEC(4, 0x98, "PortalPlayer")
JEDEC(4, 0x19, "Zhiying Software")
JEDEC(4, 0x1A, "ParkerVision, Inc.")
JEDEC(4, 0x9B, "Phonex Broadband")
JEDEC(4, 0x1C, "Skyworks Solutions")
JEDEC(4, 0x9D, "Entropic Communications")
JEDEC(4, 0x9E, "I'M Intelligent Memory Ltd.")
JEDEC(4, 0x1F, "Zensys A/S")
JEDEC(4, 0x20, "Legend Silicon Corp.")
JEDEC(4, 0xA1, "Sci-worx GmbH")
JEDEC(4, 0xA2, "SMSC (Standard Microsystems)")
JEDEC(4, 0x23, "Renesas Electronics")
JEDEC(4, 0xA4, "Raza Microelectronics")
JEDEC(4, 0x25, "Phyworks")
JEDEC(4, 0x26, "MediaTek")
JEDEC(4, 0xA7, "Non-cents Productions")
JEDEC(4, 0xA8, "US Modular")
JEDEC(4, 0x29, "Wintegra Ltd.")
JEDEC(4, 0x2A, "Mathstar")
JEDEC(4, 0xAB, "StarCore")
JEDEC(4, 0x2C, "Oplus Technologies")
JEDEC(4, 0xAD, "Mindspeed")
JEDEC(4, 0xAE, "Just Young Computer")
JEDEC(4, 0x2F, "Radia Communications")
JEDEC(4, 0xB0, "OCZ")
JEDEC(4, 0x31, "Emuzed")
JEDEC(4, 0x32, "LOGIC Devices")
JEDEC(4, 0xB3, "Inphi Corporation")
JEDEC(4, 0x34, "Quake Technologies")
JEDEC(4, 0xB5, "Vixel")
JEDEC(4, 0xB6, "SolusTek")
JEDEC(4, 0x37, "Kongsberg Maritime")
JEDEC(4, 0x38, "Faraday Technology")
JEDEC(4, 0xB9, "Altium Ltd.")
JEDEC(4, 0xBA, "Insyte")
JEDEC(4, 0x3B, "ARM Ltd.")
JEDEC(4, 0xBC, "DigiVision")
JEDEC(4, 0x3D, "Vativ Technologies")
JEDEC(4, 0x3E, "Endicott Interconnect Technologies")
JEDEC(4, 0xBF, "Pericom")
JEDEC(4, 0x40, "Bandspeed")
JEDEC(4, 0xC1, "LeWiz Communications")
JEDEC(4, 0xC2, "CPU Technology")
JEDEC(4, 0x43, "Ramaxel Technology")
JEDEC(4, 0xC4, "DSP Group")
JEDEC(4, 0x45, "Axis Communications")
JEDEC(4, 0x46, "Legacy Electronics")
JEDEC(4, 0xC7, "Chrontel")
JEDEC(4, 0xC8, "Powerchip Semiconductor")
JEDEC(4, 0x49, "MobilEye Technologies")
JEDEC(4, 0x4A, "Excel Semiconductor")
JEDEC(4, 0xCB, "A-DATA Technology")
JEDEC(4, 0x4C, "VirtualDigm")
JEDEC(4, 0xCD, "G Skill Intl")
JEDEC(4, 0xCE, "Quanta Computer")
JEDEC(4, 0x4F, "Yield Microelectronics")
JEDEC(4, 0xD0, "Afa Technologies")
JEDEC(4, 0x51, "KINGBOX Technology Co. Ltd.")
JEDEC(4, 0x52, "Ceva")
JEDEC(4, 0xD3, "iStor Networks")
JEDEC(4, 0x54, "Advance Modules")
JEDEC(4, 0xD5, "Microsoft")
JEDEC(4, 0xD6, "Open-Silicon")
JEDEC(4, 0x57, "Goal Semiconductor")
JEDEC(4, 0x58, "ARC International")
JEDEC(4, 0xD9, "Simmtec")
JEDEC(4, 0xDA, "Metanoia")
JEDEC(4, 0x5B, "Key Stream")
JEDEC(4, 0xDC, "Lowrance Electronics")
JEDEC(4, 0x5D, "Adimos")
JEDEC(4, 0x5E, "SiGe Semiconductor")
JEDEC(4, 0xDF, "Fodus Communications")
JEDEC(4, 0xE0, "Credence Systems Corp.")
JEDEC(4, 0x61, "Genesis Microchip Inc.")
JEDEC(4, 0x62, "Vihana, Inc.")
JEDEC(4, 0xE3, "WIS Technologies")
JEDEC(4, 0x64, "GateChange Technologies")
JEDEC(4, 0xE5, "High Density Devices AS")
JEDEC(4, 0xE6, "Synopsys")
JEDEC(4, 0x67, "Gigaram")
JEDEC(4, 0x68, "Enigma Semiconductor Inc.")
JEDEC(4, 0xE9, "Century Micro Inc.")
JEDEC(4, 0xEA, "Icera Semiconductor")
JEDEC(4, 0x6B, "Mediaworks Integrated Systems")
JEDEC(4, 0xEC, "O'Neil Product Development")
JEDEC(4, 0x6D, "Supreme Top Technology Ltd.")
JEDEC(4, 0x6E, "MicroDisplay Corporation")
JEDEC(4, 0xEF, "Team Group Inc.")
JEDEC(4, 0x70, "Sinett Corporation")
JEDEC(4, 0xF1, "Toshiba Corporation")
JEDEC(4, 0xF2, "Tensilica")
JEDEC(4, 0x73, "SiRF Technology")
JEDEC(4, 0xF4, "Bacoc Inc.")
JEDEC(4, 0x75, "SMaL Camera Technologies")
JEDEC(4, 0x76, "Thomson SC")
JEDEC(4, 0xF7, "Airgo Networks")
JEDEC(4, 0xF8, "Wisair Ltd.")
JEDEC(4, 0x79, "SigmaTel")
JEDEC(4, 0x7A, "Arkados")
JEDEC(4, 0xFB, "Compete IT gmbH Co. KG")
JEDEC(4, 0x7C, "Eudar Technology Inc.")
JEDEC(4, 0xFD, "Focus Enhancements")
JEDEC(4, 0xFE, "Xyratex")

JEDEC(5, 0x01, "Specular Networks")
JEDEC(5, 0x02, "Patriot Memory (PDP Systems)")
JEDEC(5, 0x83, "U-Chip Technology Corp.")
JEDEC(5, 0x04, "Silicon Optix")
JEDEC(5, 0x85, "Greenfield Networks")
JEDEC(5, 0x86, "CompuRAM GmbH")
JEDEC(5, 0x07, "Stargen, Inc.")
JEDEC(5, 0x08, "NetCell Corporation")
JEDEC(5, 0x89, "Excalibrus Technologies Ltd")
JEDEC(5, 0x8A, "SCM Microsystems")
JEDEC(5, 0x0B, "Xsigo Systems, Inc.")
JEDEC(5, 0x8C, "CHIPS & Systems Inc")
JEDEC(5, 0x13, "Tier 1 Multichip Solutions")
JEDEC(5, 0x0E, "CWRL Labs")
JEDEC(5, 0x8F, "Teradici")
JEDEC(5, 0x10, "Gigaram, Inc.")
JEDEC(5, 0x91, "g2 Microsystems")
JEDEC(5, 0x92, "PowerFlash Semiconductor")
JEDEC(5, 0x13, "P.A. Semi, Inc.")
JEDEC(5, 0x94, "NovaTech Solutions, S.A.")
JEDEC(5, 0x15, "c2 Microsystems, Inc.")
JEDEC(5, 0x16, "Level5 Networks")
JEDEC(5, 0x97, "COS Memory AG")
JEDEC(5, 0x98, "Innovasic Semiconductor")
JEDEC(5, 0x19, "IC Co. Ltd")
JEDEC(5, 0x1A, "Tabula, Inc.")
JEDEC(5, 0x9B, "Crucial Technology")
JEDEC(5, 0x1C, "Chelsio Communications")
JEDEC(5, 0x9D, "Solarflare Communications")
JEDEC(5, 0x9E, "Xambala Inc.")
JEDEC(5, 0x1F, "EADS Astrium")
JEDEC(5, 0x20, "Terra Semiconductor, Inc.")
JEDEC(5, 0xA1, "Imaging Works, Inc.")
JEDEC(5, 0xA2, "Astute Networks, Inc.")
JEDEC(5, 0x23, "Tzero")
JEDEC(5, 0xA4, "Emulex")
JEDEC(5, 0x25, "Power-One")
JEDEC(5, 0x26, "Pulse~LINK Inc.")
JEDEC(5, 0xA7, "Hon Hai Precision Industry")
JEDEC(5, 0xA8, "White Rock Networks Inc.")
JEDEC(5, 0x29, "Telegent Systems USA, Inc.")
JEDEC(5, 0x2A, "Atrua Technologies, Inc.")
JEDEC(5, 0xAB, "Acbel Polytech Inc.")
JEDEC(5, 0x2C, "eRide Inc.")
JEDEC(5, 0xAD, "ULi Electronics Inc.")
JEDEC(5, 0xAE, "Magnum Semiconductor Inc.")
JEDEC(5, 0x2F, "neoOne Technology, Inc.")
JEDEC(5, 0xB0, "Connex Technology, Inc.")
JEDEC(5, 0x31, "Stream Processors, Inc.")
JEDEC(5, 0x32, "Focus Enhancements")
JEDEC(5, 0xB3, "Telecis Wireless, Inc.")
JEDEC(5, 0x34, "uNav Microelectronics")
JEDEC(5, 0xB5, "Tarari, Inc.")
JEDEC(5, 0xB6, "Ambric, Inc.")
JEDEC(5, 0x37, "Newport Media, Inc.")
JEDEC(5, 0x38, "VMTS")
JEDEC(5, 0xB9, "Enuclia Semiconductor, Inc.")
JEDEC(5, 0xBA, "Virtium Technology Inc.")
JEDEC(5, 0x3B, "Solid State System Co., Ltd.")
JEDEC(5, 0xBC, "Kian Tech LLC")
JEDEC(5, 0x3D, "Artimi")
JEDEC(5, 0x3E, "Power Quotient International")
JEDEC(5, 0xBF, "Avago Technologies")
JEDEC(5, 0x40, "ADTechnology")
JEDEC(5, 0xC1, "Sigma Designs")
JEDEC(5, 0xC2, "SiCortex, Inc.")
JEDEC(5, 0x43, "Ventura Technology Group")
JEDEC(5, 0xC4, "eASIC")
JEDEC(5, 0x45, "M.H.S. SAS")
JEDEC(5, 0x46, "Micro Star International")
JEDEC(5, 0xC7, "Rapport Inc.")
JEDEC(5, 0xC8, "Makway International")
JEDEC(5, 0x49, "Broad Reach Engineering Co.")
JEDEC(5, 0x4A, "Semiconductor Mfg Intl Corp")
JEDEC(5, 0xCB, "SiConnect")
JEDEC(5, 0x4C, "FCI USA Inc.")
JEDEC(5, 0xCD, "Validity Sensors")
JEDEC(5, 0xCE, "Coney Technology Co. Ltd.")
JEDEC(5, 0x4F, "Spans Logic")
JEDEC(5, 0xD0, "Neterion Inc.")
JEDEC(5, 0x51, "Qimonda")
JEDEC(5, 0x52, "New Japan Radio Co. Ltd.")
JEDEC(5, 0xD3, "Velogix")
JEDEC(5, 0x54, "Montalvo Systems")
JEDEC(5, 0xD5, "iVivity Inc.")
JEDEC(5, 0xD6, "Walton Chaintech")
JEDEC(5, 0x57, "AENEON")
JEDEC(5, 0x58, "Lorom Industrial Co. Ltd.")
JEDEC(5, 0xD9, "Radiospire Networks")
JEDEC(5, 0xDA, "Sensio Technologies, Inc.")
JEDEC(5, 0x5B, "Nethra Imaging")
JEDEC(5, 0xDC, "Hexon Technology Pte Ltd")
JEDEC(5, 0x5D, "CompuStocx (CSX)")
JEDEC(5, 0x5E, "Methode Electronics, Inc.")
JEDEC(5, 0xDF, "Connect One Ltd.")
JEDEC(5, 0xE0, "Opulan Technologies")
JEDEC(5, 0x61, "Septentrio NV")
JEDEC(5, 0x62, "Goldenmars Technology Inc.")
JEDEC(5, 0xE3, "Kreton Corporation")
JEDEC(5, 0x64, "Cochlear Ltd.")
JEDEC(5, 0xE5, "Altair Semiconductor")
JEDEC(5, 0xE6, "NetEffect, Inc.")
JEDEC(5, 0x67, "Spansion, Inc.")
JEDEC(5, 0x68, "Taiwan Semiconductor Mfg")
JEDEC(5, 0xE9, "Emphany Systems Inc.")
JEDEC(5, 0xEA, "ApaceWave Technologies")
JEDEC(5, 0x6B, "Mobilygen Corporation")
JEDEC(5, 0xEC, "Tego")
JEDEC(5, 0x6D, "Cswitch Corporation")
JEDEC(5, 0x6E, "Haier (Beijing) IC Design Co.")
JEDEC(5, 0xEF, "MetaRAM")
JEDEC(5, 0x70, "Axel Electronics Co. Ltd.")
JEDEC(5, 0xF1, "Tilera Corporation")
JEDEC(5, 0xF2, "Aquantia")
JEDEC(5, 0x73, "Vivace Semiconductor")
JEDEC(5, 0xF4, "Redpine Signals")
JEDEC(5, 0x75, "Octalica")
JEDEC(5, 0x76, "InterDigital Communications")
JEDEC(5, 0xF7, "Avant Technology")
JEDEC(5, 0xF8, "Asrock, Inc.")
JEDEC(5, 0x79, "Availink")
JEDEC(5, 0x7A, "Quartics, Inc.")
JEDEC(5, 0xFB, "Element CXI")
JEDEC(5, 0x7C, "Innovaciones Microelectronicas")
JEDEC(5, 0xFD, "VeriSilicon Microelectronics")
JEDEC(5, 0xFE, "W5 Networks")

JEDEC(6, 0x01, "MOVEKING")
JEDEC(6, 0x02, "Mavrix Technology, Inc.")
JEDEC(6, 0x83, "CellGuide Ltd.")
JEDEC(6, 0x04, "Faraday Technology")
JEDEC(6, 0x85, "Diablo Technologies, Inc.")
JEDEC(6, 0x86, "Jennic")
JEDEC(6, 0x07, "Octasic")
JEDEC(6, 0x08, "Molex Incorporated")
JEDEC(6, 0x89, "Leaf Networks")
JEDEC(6, 0x8A, "Bright Micron Technology")
JEDEC(6, 0x0B, "Netxen")
JEDEC(6, 0x8C, "NextWave Broadband Inc.")
JEDEC(6, 0x0D, "DisplayLink")
JEDEC(6, 0x0E, "ZMOS Technology")
JEDEC(6, 0x8F, "Tec-Hill")
JEDEC(6, 0x10, "Multigig, Inc.")
JEDEC(6, 0x91, "Amimon")
JEDEC(6, 0x92, "Euphonic Technologies, Inc.")
JEDEC(6, 0x13, "BRN Phoenix")
JEDEC(6, 0x94, "InSilica")
JEDEC(6, 0x15, "Ember Corporation")
JEDEC(6, 0x16, "Avexir Technologies Corporation")
JEDEC(6, 0x97, "Echelon Corporation")
JEDEC(6, 0x98, "Edgewater Computer Systems")
JEDEC(6, 0x19, "XMOS Semiconductor Ltd.")
JEDEC(6, 0x1A, "GENUSION, Inc.")
JEDEC(6, 0x9B, "Memory Corp NV")
JEDEC(6, 0x1C, "SiliconBlue Technologies")
JEDEC(6, 0x9D, "Rambus Inc.")
JEDEC(6, 0x9E, "Andes Technology Corporation")
JEDEC(6, 0x1F, "Coronis Systems")
JEDEC(6, 0x20, "Achronix Semiconductor")
JEDEC(6, 0xA1, "Siano Mobile Silicon Ltd.")
JEDEC(6, 0xA2, "Semtech Corporation")
JEDEC(6, 0x23, "Pixelworks Inc.")
JEDEC(6, 0xA4, "Gaisler Research AB")
JEDEC(6, 0x25, "Teranetics")
JEDEC(6, 0x26, "Toppan Printing Co. Ltd.")
JEDEC(6, 0xA7, "Kingxcon")
JEDEC(6, 0xA8, "Silicon Integrated Systems")
JEDEC(6, 0x29, "I-O Data Device, Inc.")
JEDEC(6, 0x2A, "NDS Americas Inc.")
JEDEC(6, 0xAB, "Solomon Systech Limited")
JEDEC(6, 0x2C, "On Demand Microelectronics")
JEDEC(6, 0xAD, "Amicus Wireless Inc.")
JEDEC(6, 0xAE, "SMARDTV SNC")
JEDEC(6, 0x2F, "Comsys Communication Ltd.")
JEDEC(6, 0xB0, "Movidia Ltd.")
JEDEC(6, 0x31, "Javad GNSS, Inc.")
JEDEC(6, 0x32, "Montage Technology Group")
JEDEC(6, 0xB3, "Trident Microsystems")
JEDEC(6, 0x34, "Super Talent")
JEDEC(6, 0xB5, "Optichron, Inc.")
JEDEC(6, 0xB6, "Future Waves UK Ltd.")
JEDEC(6, 0x37, "SiBEAM, Inc.")
JEDEC(6, 0x38, "Inicore,Inc.")
JEDEC(6, 0xB9, "Virident Systems")
JEDEC(6, 0x00, "M2")JEDEC(6, 0xBA, ", Inc.")
JEDEC(6, 0x3B, "ZeroG Wireless, Inc.")
JEDEC(6, 0xBC, "Gingle Technology Co. Ltd.")
JEDEC(6, 0x3D, "Space Micro Inc.")
JEDEC(6, 0x3E, "Wilocity")
JEDEC(6, 0xBF, "Novafora, Inc.")
JEDEC(6, 0x40, "iKoa Corporation")
JEDEC(6, 0xC1, "ASint Technology")
JEDEC(6, 0xC2, "Ramtron")
JEDEC(6, 0x43, "Plato Networks Inc.")
JEDEC(6, 0xC4, "IPtronics AS")
JEDEC(6, 0x45, "Infinite-Memories")
JEDEC(6, 0x46, "Parade Technologies Inc.")
JEDEC(6, 0xC7, "Dune Networks")
JEDEC(6, 0xC8, "GigaDevice Semiconductor")
JEDEC(6, 0x49, "Modu Ltd.")
JEDEC(6, 0x4A, "CEITEC")
JEDEC(6, 0xCB, "Northrop Grumman")
JEDEC(6, 0x4C, "XRONET Corporation")
JEDEC(6, 0xCD, "Sicon Semiconductor AB")
JEDEC(6, 0xCE, "Atla Electronics Co. Ltd.")
JEDEC(6, 0x4F, "TOPRAM Technology")
JEDEC(6, 0xD0, "Silego Technology Inc.")
JEDEC(6, 0x51, "Kinglife")
JEDEC(6, 0x52, "Ability Industries Ltd.")
JEDEC(6, 0xD3, "Silicon Power Computer & Communications")
JEDEC(6, 0x54, "Augusta Technology, Inc.")
JEDEC(6, 0xD5, "Nantronics Semiconductors")
JEDEC(6, 0xD6, "Hilscher Gesellschaft")
JEDEC(6, 0x57, "Quixant Ltd.")
JEDEC(6, 0x58, "Percello Ltd.")
JEDEC(6, 0xD9, "NextIO Inc.")
JEDEC(6, 0xDA, "Scanimetrics Inc.")
JEDEC(6, 0x5B, "FS-Semi Company Ltd.")
JEDEC(6, 0xDC, "Infinera Corporation")
JEDEC(6, 0x5D, "SandForce Inc.")
JEDEC(6, 0x5E, "Lexar Media")
JEDEC(6, 0xDF, "Teradyne Inc.")
JEDEC(6, 0xE0, "Memory Exchange Corp.")
JEDEC(6, 0x61, "Suzhou Smartek Electronics")
JEDEC(6, 0x62, "Avantium Corporation")
JEDEC(6, 0xE3, "ATP Electronics Inc.")
JEDEC(6, 0x64, "Valens Semiconductor Ltd")
JEDEC(6, 0xE5, "Agate Logic, Inc.")
JEDEC(6, 0xE6, "Netronome")
JEDEC(6, 0x67, "Zenverge, Inc.")
JEDEC(6, 0x68, "N-trig Ltd")
JEDEC(6, 0xE9, "SanMax Technologies Inc.")
JEDEC(6, 0xEA, "Contour Semiconductor Inc.")
JEDEC(6, 0x6B, "TwinMOS")
JEDEC(6, 0xEC, "Silicon Systems, Inc.")
JEDEC(6, 0x6D, "V-Color Technology Inc.")
JEDEC(6, 0x6E, "Certicom Corporation")
JEDEC(6, 0xEF, "JSC ICC Milandr")
JEDEC(6, 0x70, "PhotoFast Global Inc.")
JEDEC(6, 0xF1, "InnoDisk Corporation")
JEDEC(6, 0xF2, "Muscle Power")
JEDEC(6, 0x73, "Energy Micro")
JEDEC(6, 0xF4, "Innofidei")
JEDEC(6, 0x75, "CopperGate Communications")
JEDEC(6, 0x76, "Holtek Semiconductor Inc.")
JEDEC(6, 0xF7, "Myson Century, Inc.")
JEDEC(6, 0xF8, "FIDELIX")
JEDEC(6, 0x79, "Red Digital Cinema")
JEDEC(6, 0x7A, "Densbits Technology")
JEDEC(6, 0xFB, "Zempro")
JEDEC(6, 0x7C, "MoSys")
JEDEC(6, 0xFD, "Provigent")
JEDEC(6, 0xFE, "Triad Semiconductor, Inc.")

JEDEC(7, 0x01, "Siklu Communication Ltd.")
JEDEC(7, 0x02, "A Force Manufacturing Ltd.")
JEDEC(7, 0x83, "Strontium")
JEDEC(7, 0x04, "ALi Corp (Abilis Systems)")
JEDEC(7, 0x85, "Siglead, Inc.")
JEDEC(7, 0x86, "Ubicom, Inc.")
JEDEC(7, 0x07, "Unifosa Corporation")
JEDEC(7, 0x08, "Stretch, Inc.")
JEDEC(7, 0x89, "Lantiq Deutschland GmbH")
JEDEC(7, 0x8A, "Visipro.")
JEDEC(7, 0x0B, "EKMemory")
JEDEC(7, 0x8C, "Microelectronics Institute ZTE")
JEDEC(7, 0x0D, "Cognovo Ltd.")
JEDEC(7, 0x0E, "Carry Technology Co. Ltd.")
JEDEC(7, 0x8F, "Nokia")
JEDEC(7, 0x10, "King Tiger Technology")
JEDEC(7, 0x91, "Sierra Wireless")
JEDEC(7, 0x92, "HT Micron")
JEDEC(7, 0x13, "Albatron Technology Co. Ltd.")
JEDEC(7, 0x94, "Leica Geosystems AG")
JEDEC(7, 0x15, "BroadLight")
JEDEC(7, 0x16, "AEXEA")
JEDEC(7, 0x97, "ClariPhy Communications, Inc.")
JEDEC(7, 0x98, "Green Plug")
JEDEC(7, 0x19, "Design Art Networks")
JEDEC(7, 0x1A, "Mach Xtreme Technology Ltd.")
JEDEC(7, 0x9B, "ATO Solutions Co. Ltd.")
JEDEC(7, 0x1C, "Ramsta")
JEDEC(7, 0x9D, "Greenliant Systems, Ltd.")
JEDEC(7, 0x9E, "Teikon")
JEDEC(7, 0x1F, "Antec Hadron")
JEDEC(7, 0x20, "NavCom Technology, Inc.")
JEDEC(7, 0xA1, "Shanghai Fudan Microelectronics")
JEDEC(7, 0xA2, "Calxeda, Inc.")
JEDEC(7, 0x23, "JSC EDC Electronics")
JEDEC(7, 0xA4, "Kandit Technology Co. Ltd.")
JEDEC(7, 0x25, "Ramos Technology")
JEDEC(7, 0x26, "Goldenmars Technology")
JEDEC(7, 0xA7, "XeL Technology Inc.")
JEDEC(7, 0xA8, "Newzone Corporation")
JEDEC(7, 0x29, "ShenZhen MercyPower Tech")
JEDEC(7, 0x2A, "Nanjing Yihuo Technology")
JEDEC(7, 0xAB, "Nethra Imaging Inc.")
JEDEC(7, 0x2C, "SiTel Semiconductor BV")
JEDEC(7, 0xAD, "SolidGear Corporation")
JEDEC(7, 0xAE, "Topower Computer Ind Co Ltd.")
JEDEC(7, 0x2F, "Wilocity")
JEDEC(7, 0xB0, "Profichip GmbH")
JEDEC(7, 0x31, "Gerad Technologies")
JEDEC(7, 0x32, "Ritek Corporation")
JEDEC(7, 0xB3, "Gomos Technology Limited")
JEDEC(7, 0x34, "Memoright Corporation")
JEDEC(7, 0xB5, "D-Broad, Inc.")
JEDEC(7, 0xB6, "HiSilicon Technologies")
JEDEC(7, 0x37, "Syndiant Inc..")
JEDEC(7, 0x38, "Enverv Inc.")
JEDEC(7, 0xB9, "Cognex")
JEDEC(7, 0xBA, "Xinnova Technology Inc.")
JEDEC(7, 0x3B, "Ultron AG")
JEDEC(7, 0xBC, "Concord Idea Corporation")
JEDEC(7, 0x3D, "AIM Corporation")
JEDEC(7, 0x3E, "Lifetime Memory Products")
JEDEC(7, 0xBF, "Ramsway")
JEDEC(7, 0x40, "Recore Systems B.V.")
JEDEC(7, 0xC1, "Haotian Jinshibo Science Tech")
JEDEC(7, 0xC2, "Being Advanced Memory")
JEDEC(7, 0x43, "Adesto Technologies")
JEDEC(7, 0xC4, "Giantec Semiconductor, Inc.")
JEDEC(7, 0x45, "HMD Electronics AG")
JEDEC(7, 0x46, "Gloway International (HK)")
JEDEC(7, 0xC7, "Kingcore")
JEDEC(7, 0xC8, "Anucell Technology Holding")
JEDEC(7, 0x49, "Accord Software & Systems Pvt. Ltd.")
JEDEC(7, 0x4A, "Active-Semi Inc.")
JEDEC(7, 0xCB, "Denso Corporation")
JEDEC(7, 0x4C, "TLSI Inc.")
JEDEC(7, 0xCD, "Qidan")
JEDEC(7, 0xCE, "Mustang")
JEDEC(7, 0x4F, "Orca Systems")
JEDEC(7, 0xD0, "Passif Semiconductor")
JEDEC(7, 0x51, "GigaDevice Semiconductor (Beijing) Inc.")
JEDEC(7, 0x52, "Memphis Electronic")
JEDEC(7, 0xD3, "Beckhoff Automation GmbH")
JEDEC(7, 0x54, "Harmony Semiconductor Corp")
JEDEC(7, 0xD5, "Air Computers SRL")
JEDEC(7, 0xD6, "TMT Memory")
JEDEC(7, 0x57, "Eorex Corporation")
JEDEC(7, 0x58, "Xingtera")
JEDEC(7, 0xD9, "Netsol")
JEDEC(7, 0xDA, "Bestdon Technology Co. Ltd.")
JEDEC(7, 0x5B, "Baysand Inc.")
JEDEC(7, 0xDC, "Uroad Technology Co. Ltd.")
JEDEC(7, 0x5D, "Wilk Elektronik S.A.")
JEDEC(7, 0x5E, "AAI")
JEDEC(7, 0xDF, "Harman")
JEDEC(7, 0xE0, "Berg Microelectronics Inc.")
JEDEC(7, 0x61, "ASSIA, Inc.")
JEDEC(7, 0x62, "Visiontek Products LLC")
JEDEC(7, 0xE3, "OCMEMORY")
JEDEC(7, 0x64, "Welink Solution Inc.")
JEDEC(7, 0xE5, "Shark Gaming")
JEDEC(7, 0xE6, "Avalanche Technology")
JEDEC(7, 0x67, "R&D Center ELVEES OJSC")
JEDEC(7, 0x68, "KingboMars Technology Co. Ltd.")
JEDEC(7, 0xE9, "High Bridge Solutions Industria Eletronica")
JEDEC(7, 0xEA, "Transcend Technology Co. Ltd.")
JEDEC(7, 0x6B, "Everspin Technologies")
JEDEC(7, 0xEC, "Hon-Hai Precision")
JEDEC(7, 0x6D, "Smart Storage Systems")
JEDEC(7, 0x6E, "Toumaz Group")
JEDEC(7, 0xEF, "Zentel Electronics Corporation")
JEDEC(7, 0x70, "Panram International Corporation")
JEDEC(7, 0xF1, "Silicon Space Technology")
JEDEC(7, 0xF2, "LITE-ON IT Corporation")
JEDEC(7, 0x73, "Inuitive")
JEDEC(7, 0xF4, "HMicro")
JEDEC(7, 0x75, "BittWare, Inc.")
JEDEC(7, 0x76, "GLOBALFOUNDRIES")
JEDEC(7, 0xF7, "ACPI Digital Co. Ltd.")
JEDEC(7, 0xF8, "Annapurna Labs")
JEDEC(7, 0x79, "AcSiP Technology Corporation")
JEDEC(7, 0x7A, "Idea! Electronic Systems")
JEDEC(7, 0xFB, "Gowe Technology Co. Ltd.")
JEDEC(7, 0x7C, "Hermes Testing Solutions, Inc.")
JEDEC(7, 0xFD, "Positivo BGH")
JEDEC(7, 0xFE, "Intelligence Silicon Technology")

JEDEC(8, 0x01, "D PLUS")
JEDEC(8, 0x02, "Diehl Aerospace")
JEDEC(8, 0x83, "Fairchild")
JEDEC(8, 0x04, "Mercury Systems")
JEDEC(8, 0x85, "Sonics, Inc.")
JEDEC(8, 0x86, "GE Intelligent Platforms GmbH & Co.")
JEDEC(8, 0x07, "Shenzhen Jinge Information Co. Ltd.")
JEDEC(8, 0x08, "SCWW")
JEDEC(8, 0x89, "Silicon Motion Inc.")
JEDEC(8, 0x8A, "Anurag")
JEDEC(8, 0x0B, "King Kong")
JEDEC(8, 0x30, "FROM")JEDEC(8, 0x8C, "Co. Ltd.")
JEDEC(8, 0x0D, "Gowin Semiconductor Corp")
JEDEC(8, 0x0E, "Fremont Micro Devices Ltd.")
JEDEC(8, 0x8F, "Ericsson Modems")
JEDEC(8, 0x10, "Exelis")
JEDEC(8, 0x91, "Satixfy Ltd.")
JEDEC(8, 0x92, "Galaxy Microsystems Ltd.")
JEDEC(8, 0x13, "Gloway International Co. Ltd.")
JEDEC(8, 0x94, "Lab")
JEDEC(8, 0x15, "Smart Energy Instruments")
JEDEC(8, 0x16, "Approved Memory Corporation")
JEDEC(8, 0x97, "Axell Corporation")
JEDEC(8, 0x98, "Essencore Limited")
JEDEC(8, 0x19, "Phytium")
JEDEC(8, 0x1A, "Xi’an SinoChip Semiconductor")
JEDEC(8, 0x9B, "Ambiq Micro")
JEDEC(8, 0x1C, "eveRAM Technology, Inc.")
JEDEC(8, 0x9D, "Infomax")
JEDEC(8, 0x9E, "Butterfly Network, Inc.")
JEDEC(8, 0x1F, "Shenzhen City Gcai Electronics")
JEDEC(8, 0x20, "Stack Devices Corporation")
JEDEC(8, 0xA1, "ADK Media Group")
JEDEC(8, 0xA2, "TSP Global Co., Ltd.")
JEDEC(8, 0x23, "HighX")
JEDEC(8, 0xA4, "Shenzhen Elicks Technology")
JEDEC(8, 0x25, "ISSI/Chingis")
JEDEC(8, 0x26, "Google, Inc.")
JEDEC(8, 0xA7, "Dasima International Development")
JEDEC(8, 0xA8, "Leahkinn Technology Limited")
JEDEC(8, 0x29, "HIMA Paul Hildebrandt GmbH Co KG")
JEDEC(8, 0x2A, "Keysight Technologies")
JEDEC(8, 0xAB, "Techcomp International (Fastable)")
JEDEC(8, 0x2C, "Ancore Technology Corporation")
JEDEC(8, 0xAD, "Nuvoton")
JEDEC(8, 0xAE, "Korea Uhbele International Group Ltd.")
JEDEC(8, 0x2F, "Ikegami Tsushinki Co Ltd.")
JEDEC(8, 0xB0, "RelChip, Inc.")
JEDEC(8, 0x31, "Baikal Electronics")
JEDEC(8, 0x32, "Nemostech Inc.")
JEDEC(8, 0xB3, "Memorysolution GmbH")
JEDEC(8, 0x34, "Silicon Integrated Systems Corporation")
JEDEC(8, 0xB5, "Xiede")
JEDEC(8, 0xB6, "Multilaser Components")
JEDEC(8, 0x37, "Flash Chi")
JEDEC(8, 0x38, "Jone")
JEDEC(8, 0xB9, "GCT Semiconductor Inc.")
JEDEC(8, 0xBA, "Hong Kong Zetta Device Technology")
JEDEC(8, 0x3B, "Unimemory Technology(s) Pte Ltd.")
JEDEC(8, 0xBC, "Cuso")
JEDEC(8, 0x3D, "Kuso")
JEDEC(8, 0x3E, "Uniquify Inc.")
JEDEC(8, 0xBF, "Skymedi Corporation")
JEDEC(8, 0x40, "Core Chance Co. Ltd.")
JEDEC(8, 0xC1, "Tekism Co. Ltd.")
JEDEC(8, 0xC2, "Seagate Technology PLC")
JEDEC(8, 0x43, "Hong Kong Gaia Group Co. Limited")
JEDEC(8, 0xC4, "Gigacom Semiconductor LLC")
JEDEC(8, 0x45, "V2 Technologies")
JEDEC(8, 0x46, "TLi")
JEDEC(8, 0xC7, "Neotion")
JEDEC(8, 0xC8, "Lenovo")
JEDEC(8, 0x49, "Shenzhen Zhongteng Electronic Corp. Ltd.")
JEDEC(8, 0x4A, "Compound Photonics")
JEDEC(8, 0xCB, "in2H2 inc")
JEDEC(8, 0x4C, "Shenzhen Pango Microsystems Co. Ltd")
JEDEC(8, 0xCD, "Vasekey")
JEDEC(8, 0xCE, "Cal-Comp Industria de Semicondutores")
JEDEC(8, 0x4F, "Eyenix Co., Ltd.")
JEDEC(8, 0xD0, "Heoriady")
JEDEC(8, 0x51, "Accelerated Memory Production Inc.")
JEDEC(8, 0x52, "INVECAS, Inc.")
JEDEC(8, 0xD3, "AP Memory")
JEDEC(8, 0x54, "Douqi Technology")
JEDEC(8, 0xD5, "Etron Technology, Inc.")
JEDEC(8, 0xD6, "Indie Semiconductor")
JEDEC(8, 0x57, "Socionext Inc.")
JEDEC(8, 0x58, "HGST")
JEDEC(8, 0xD9, "EVGA")
JEDEC(8, 0xDA, "Audience Inc.")
JEDEC(8, 0x5B, "EpicGear")
JEDEC(8, 0xDC, "Vitesse Enterprise Co.")
JEDEC(8, 0x5D, "Foxtronn International Corporation")
JEDEC(8, 0x5E, "Bretelon Inc.")
JEDEC(8, 0xDF, "Zbit Semiconductor, Inc.")
JEDEC(8, 0xE0, "Eoplex Inc")
JEDEC(8, 0x61, "MaxLinear, Inc.")
JEDEC(8, 0x62, "ETA Devices")
JEDEC(8, 0xE3, "LOKI")
JEDEC(8, 0x64, "IMS Semiconductor Co., Ltd")
JEDEC(8, 0xE5, "Dosilicon Co., Ltd.")
JEDEC(8, 0xE6, "Dolphin Integration")
JEDEC(8, 0x67, "Shenzhen Mic Electronics Technology")
JEDEC(8, 0x68, "Boya Microelectronics Inc.")
JEDEC(8, 0xE9, "Geniachip (Roche)")
JEDEC(8, 0xEA, "Axign")
JEDEC(8, 0x6B, "Kingred Electronic Technology Ltd.")
JEDEC(8, 0xEC, "Chao Yue Zhuo Computer Business Dept.")
JEDEC(8, 0x6D, "Guangzhou Si Nuo Electronic Technology.")
JEDEC(8, 0x6E, "Crocus Technology Inc.")
JEDEC(8, 0xEF, "Creative Chips GmbH")
JEDEC(8, 0x70, "GE Aviation Systems LLC.")
JEDEC(8, 0xF1, "Asgard")
JEDEC(8, 0xF2, "Good Wealth Technology Ltd.")
JEDEC(8, 0x73, "TriCor Technologies")
JEDEC(8, 0xF4, "Nova-Systems GmbH")
JEDEC(8, 0x75, "JUHOR")
JEDEC(8, 0x76, "Zhuhai Douke Commerce Co. Ltd.")
JEDEC(8, 0xF7, "DSL Memory")
JEDEC(8, 0xF8, "Anvo-Systems Dresden GmbH")
JEDEC(8, 0x79, "Realtek")
JEDEC(8, 0x7A, "AltoBeam")
JEDEC(8, 0xFB, "Wave Computing")
JEDEC(8, 0x7C, "Beijing TrustNet Technology Co. Ltd.")
JEDEC(8, 0xFD, "Innovium, Inc.")
JEDEC(8, 0xFE, "Starsway Technology Limited")

JEDEC(9, 0x01, "Weltronics Co. LTD")
JEDEC(9, 0x02, "VMware, Inc.")
JEDEC(9, 0x83, "Hewlett Packard Enterprise")
JEDEC(9, 0x04, "INTENSO")
JEDEC(9, 0x85, "Puya Semiconductor")
JEDEC(9, 0x86, "MEMORFI")
JEDEC(9, 0x07, "MSC Technologies GmbH")
JEDEC(9, 0x08, "Txrui")
JEDEC(9, 0x89, "SiFive, Inc.")
JEDEC(9, 0x8A, "Spreadtrum Communications")
